name: CityBuildSystem
author: XenoDEV
version: 1.3
main: main.java.de.xenodev.cbs.main.Main

commands:
  money:
    description: Benutze das Coin System oder zeige deine Coins an
  bank:
    description: benutze das Bank System oder zeige deine Bank an
  ticket:
    description: benutze das Ticket System
  trade:
    description: benutze das Bank System zu überweisen
  oz:
    description: siehe die Onlinezeit
  ot:
    description: siehe die Onlinezeit
  onlinezeit:
    description: siehe die Onlinezeit
  onlinetime:
    description: siehe die Onlinezeit