name: SkyWars
version: ${project.version}
main: de.poxh.skywars.main.Main
api-version: 1.16
authors: [PoxhYT, SolomonRosemite]
commands:
  start:
  build:
  create:
  location:
  createBlock:
  setup:
  addItem:
  enchantAll:
  forceStart:
