name: CityBuildAddon
version: 1.0
author: PoxhYT
main: de.cba.main.Main
commands:
   inv:
     description: Lade, oder speicher dein Inventar.
   invsee:
     description: Gucke das Inventar anderer Spieler an.
   coins:
     description: Zeigt die Coins von dir, und andere Spieler an.




